### ISSUE TITLE
BESC30-R1 CAD File Missing

### ISSUE THREAD

**Issue by thomasshim93** [bluerobotics/bluerobotics.github.io#1]
Hi, I wanted to download the CAD file for the Basic ESC, but all the links are broken.

**Comment by rjehangir** [comment]
Hi Thomas,

Good catch. We'll try to have that file updated within a few days. Please check back then.

Best,

Rusty

**Comment by rjehangir** [comment]
Sorry for the delay, but the files have been added and the links fixed!

-Rusty
