### ISSUE TITLE
Doc hasn't a detailed description of LED indicator light behavior?

### ISSUE THREAD

**Issue by bnwn** [bluerobotics/bluerobotics.github.io#17]

**Comment by rjehangir** [comment]
@bnwn Thanks for posting this issue. Are you talking about the LED indicator on the BlueESC, Basic ESC, something else? We can definitely add this.

**Comment by bnwn** [comment]
Hi Rustom,
 i use the BlueESC. If i want to change firmware for esc with simonk bootloader, in addtion to Turnigy USB Linker, what USB linker/ programmer i can also use??
Grateful for yo reply.

**Comment by jaxxzer** [comment]
Closing with `wontfix` as the BlueESC is no longer produced.
