### ISSUE TITLE
Suggestion- Vacuum test

### ISSUE THREAD

**Issue by DTopland** [bluerobotics/bluerobotics.github.io#20]
The vacuum test for the telemetry can should be done **between** the two o-rings, not the entire can. When testing the whole can you need a huge leakage to be able to read the leakage on the gauge. A small leakage like a hair or some rag on the o-rings will not bee seen unless the test last for very extended periods. 
**Measuring between the o-rings test both o-rings.** Today's test only require one o-ring to be OK in order to pass the test.  
It is not a question IF but WHEN you forget to put back the vacuum test cap. If the vacuum test vent goes between the O-rings, the area between the two o-rings will be flooded but not the telemetry can, unless the inner o-ring fails. In that case the technician should have experienced that the vacuum test failed prior to put the vehicle in water.

**Comment by jaxxzer** [comment]
You are correct that passing a pressure test with both seals installed does not _necessarily_ mean that the integrity of both seals is maintained, only that at least one of them is. I don't know if it would be possible to test both seals individually without invalidating the results by unsealing the container between tests.

The redundancy provided by the double o-ring seal makes it twice as likely that you will pass the test, which is still useful, and still provides redundancy at depth when both seals are in fact maintained.

In practice, the radial o ring seals very rarely fail.
