### ISSUE TITLE
something about how to use VS2012 to run the ROV2’s control program

### ISSUE THREAD

**Issue by strawrryhyy** [bluerobotics/bluerobotics.github.io#25]
Dear designer:
Firstly,i want know where i can get the ROV2's control program.
Secondly,i want know how to use VS2012 to run it.
that's all.
thank you.

**Comment by rjehangir** [comment]
Hi @strawrryhyy, the BlueROV2 uses the [ArduSub](http://github.com/bluerobotics/ardusub/) software. It cannot be run in VS2012. It's designed for embedded use on the Pixhawk and other autopilots.
