### ISSUE TITLE
No 'TX mode' selection available in QGroundControl

### ISSUE THREAD

**Issue by pvazteixeira** [bluerobotics/bluerobotics.github.io#27]
In the 'Joystick/Gamepad Calibration' Step of the manual, step 2 states:

`Ensure the ‘TX Mode’ selection is set to 3`

In QGroundControl v3.1.3 there is no TX Mode selection GUI element.

**Comment by Williangalvani** [comment]
It works fine in master: 
![Screenshot from 2019-03-25 09-15-47](https://user-images.githubusercontent.com/4013804/54919106-b6e9e980-4ede-11e9-832f-e481fb6e1b3a.png)
