### ISSUE TITLE
Motors won't spin

### ISSUE THREAD

**Issue by henrys-code** [bluerobotics/bluerobotics.github.io#44]
Hello,
I purchased 6 of your new model of ESCs and have them connected to a pixhawk with ardusub firmware 3.5.2 stable version git revision 07f2d5ac, which is connected over usb to an nvidia jetson tx2 which is running mavproxy to connect over ethernet to a laptop running qground control, which has a logitech f310 controller plugged in. I am able to arm and disarm the controller with the start and select buttons but when I move the joysticks the motors do not spin. Do the ESCs need calibrated? I have tested them with a servo tester and they all work fine and spin the motors, but they don't work when connected to pixhawk. Any help would be great, thanks!

**Comment by Williangalvani** [comment]
Please keep support questions to https://discuss.bluerobotics.com/ or support@bluerobotics.com
