### ISSUE TITLE
Software setup - dependencies on Ubuntu 18.04

### ISSUE THREAD

**Issue by dgomezibanez** [bluerobotics/bluerobotics.github.io#52]
Software setup instructions, or else the QGroundControl appimage, should be updated for Ubuntu 18.04.

Attempted to run QGroundControl AppImage with a fresh install of Ubuntu 18.04 LTS. I found it was necessary to install two dependencies:

sudo apt-get install espeak (to get it to run at all)
sudo apt-get install gstreamer1.0-plugins-bad (for video to work)

OS was Ubuntu 18.04
QGroundControl version 3.2.4-BlueRobotics-Rev5

**Comment by Williangalvani** [comment]
I just checked with a fresh Ubuntu 18.04 VM that the instructions here: https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html#ubuntu are enough.
