### ISSUE TITLE
Add missing cad models

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/bluerobotics.github.io#62]

**Comment by jaxxzer** [comment]
Some that we need are here: https://github.com/bluerobotics/bluerobotics.github.io/pull/60

**Comment by Bobsthinking** [comment]
Hi! can i do all of cad models that are missing?

**Comment by kklemens** [comment]
Every product now has a 2D Drawing and 3D Model, the big ones are on GrabCAD.
