### ISSUE TITLE
New I2C adress after update

### ISSUE THREAD

**Issue by agademer** [bluerobotics/bluerobotics.github.io#9]
default I2C address for the blueESC is 0x29

after update the firmware with the "blueesc_id1.hex" file, it would be intuitive that the new I2C address should be 0x01... but in reality it is : 0x29 + 1 = 0x2A !

You may add this unwritten rule to the documentation page to avoid some pain (and panic) to the futur users :)

To find the address of an unknown BlueESC we have made the following code that we are happy to share with the community

[I2CSeekAddress.zip](https://github.com/bluerobotics/bluerobotics.github.io/files/308759/I2CSeekAddress.zip)

Thank you for your beautiful motors :)

**Comment by jaxxzer** [comment]
Closing with `wontfix` as the BlueESC is no longer in production.
